name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        include:
          - app_binary: default_linker
          - app_binary: default_linker.exe
            os: windows
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release
        working-directory: ./app
      - run: zip ext.zip icon.png manifest.json sw.js
        working-directory: ./ext
      - run: mv app/target/release/${{ matrix.app_binary }} ext/ext.zip .
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: |
            ${{ matrix.app_binary }}
            ext.zip
          if-no-files-found: error
