name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release
        working-directory: ./app
      - run: zip ext.zip icon.png manifest.json sw.js
        working-directory: ./ext
      - uses: actions/upload-artifact@v4
        with:
          name: extension
          path: ext/ext.zip
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        with:
          name: app-linux
          path: app/target/release/default_linker
          if-no-files-found: error
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release
        working-directory: ./app
      - uses: actions/upload-artifact@v4
        with:
          name: app-macos
          path: app/target/release/default_linker
          if-no-files-found: error
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release
        working-directory: ./app
      - uses: actions/upload-artifact@v4
        with:
          name: app-windows
          path: app/target/release/default_linker.exe
          if-no-files-found: error
