name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  app:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        include:
          - app_binary: default_linker
          - app_binary: default_linker.exe
            os: windows
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release
        working-directory: ./app
      - uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}
          path: app/target/release/${{ matrix.app_binary }}
          if-no-files-found: error
  ext:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: extension
          path: |
            ext/icon.png
            ext/manifest.json
            ext/sw.js
          if-no-files-found: error
